<?php

namespace App\Models\Util;


class Avaliacao
{   
    const ENSINO_AULA = 1;
    const ENSINO_COORDENACAO_REGENCIA = 2;
    const ENSINO_ORIENTACAO = 3;
    const ENSINO_SUPERVISAO = 4;
    const ENSINO_ATENDIMENTO_DISCENTE = 5;
    const ENSINO_PROJETO = 6;
    const ENSINO_PARTICIPACAO = 7;
    const ENSINO_MEMBRO_DOCENTE = 8;

    const PESQUISA_COORDENACAO = 9;
    const PESQUISA_ORIENTACAO = 10;
    const PESQUISA_LIDERANCA = 11;

    const EXTENSAO_COORDENACAO = 12;
    const EXTENSAO_ORIENTACAO = 13;

    CONST GESTAO_COORDENACAO_LABORATORIOS_DIDATICOS = 14;
    CONST GESTAO_MEMBRO_CONSELHO = 15;
    CONST GESTAO_COORDENACAO_PROGRAMA_INSTITUCIONAL = 16;
    CONST GESTAO_MEMBRO_TITULAR_CONSELHO = 17;
    CONST GESTAO_MEMBRO_CAMARAS = 18;
    CONST GESTAO_REPRESENTANTE_UNIDADE_EDUCACAO = 19;
    CONST GESTAO_MEMBRO_COMISSAO = 20;
    
}