<?php

namespace App\Models\Util;


class Avaliacao
{   
    const ENSINO_AULA = 1;
    const ENSINO_COORDENACAO_REGENCIA = 2;
    const ENSINO_ORIENTACAO = 3;
    const ENSINO_SUPERVISAO = 4;
    const ENSINO_ATENDIMENTO_DISCENTE = 5;
    const ENSINO_PROJETO = 6;
    const ENSINO_PARTICIPACAO = 7;
    const ENSINO_MEMBRO_DOCENTE = 8;
    const ENSINO_OUTROS = 9;

    const PESQUISA_COORDENACAO = 10;
    const PESQUISA_ORIENTACAO = 11;
    const PESQUISA_LIDERANCA = 12;
    const PESQUISA_OUTROS = 13;

    const EXTENSAO_COORDENACAO = 14;
    const EXTENSAO_ORIENTACAO = 15;
    const EXTENSAO_OUTROS = 16;

    CONST GESTAO_COORDENACAO_LABORATORIOS_DIDATICOS = 17;
    CONST GESTAO_MEMBRO_CONSELHO = 18;
    CONST GESTAO_COORDENACAO_PROGRAMA_INSTITUCIONAL = 19;
    CONST GESTAO_MEMBRO_TITULAR_CONSELHO = 20;
    CONST GESTAO_MEMBRO_CAMARAS = 21;
    CONST GESTAO_REPRESENTANTE_UNIDADE_EDUCACAO = 22;
    CONST GESTAO_MEMBRO_COMISSAO = 23;
    CONST GESTAO_OUTROS = 24;
}
